[package]
name = "rnote-export"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
glob = "0.3.1"
serde = { version = "1.0.214", features = ["derive"] }
toml = "0.8.19"
